export enum CIFX_BUS_STATE {
	CIFX_BUS_STATE_OFF = 0,
	CIFX_BUS_STATE_ON = 1,
	CIFX_BUS_STATE_GETSTATE = 2
}

export enum CIFX_HOST_STATE {
	CIFX_HOST_STATE_NOT_READY = 0,
	CIFX_HOST_STATE_READY = 1,
	CIFX_HOST_STATE_READ = 2
}

export enum CIFX_CONFIGURATION {
	CIFX_CONFIGURATION_UNLOCK = 0,
	CIFX_CONFIGURATION_LOCK = 1,
	CIFX_CONFIGURATION_GETLOCKSTATE = 2
}

export enum CIFX_RESET {
	CIFX_SYSTEMSTART = 1,
	CIFX_CHANNELINIT = 2,
	CIFX_BOOTSTART = 3
}

export const CIFX_IO_WAIT_TIMEOUT = 40;
export const CIFX_UPDATE_STATE_WAIT_TIMEOUT = 5000;